- name: "Testa conex√£o"
  community.postgresql.postgresql_query:
    login_host: "{{ db.host }}"
    login_port: "{{ db.port }}"
    login_db: "{{ db.name }}"
    login_user: "{{ db.user }}"
    query: "SELECT 1 "
  register: conntest
